'use strict';function u(f,a,b,d){f.u.uc(f.cb,a,b,d,void 0)}function H(f,a,b,d){f.u.ca?u(f,a,b,d):f.u.rf()._OnMessageFromDOM({type:"event",component:f.cb,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function I(f,a,b){f.u.C(f.cb,a,b)}function K(f,a){for(const [b,d]of a)I(f,b,d)}function M(f){f.Ub||(f.u.af(f.ke),f.Ub=!0)}window.ua=class{constructor(f,a){this.u=f;this.cb=a;this.Ub=!1;this.ke=()=>this.Ga()}od(){}Ga(){}};function N(f){-1!==f.Ta&&(self.clearTimeout(f.Ta),f.Ta=-1)}
window.Se=class{constructor(f,a){this.Vc=f;this.Eg=a;this.Ta=-1;this.Vb=-Infinity;this.le=()=>{this.Ta=-1;this.Vb=Date.now();this.ib=!0;this.Vc();this.ib=!1};this.Td=this.ib=!1}f(){N(this);this.le=this.Vc=null}};"use strict";function O(f,a){I(f,"get-element",b=>{const d=f.ba.get(b.elementId);return a(d,b)})}
window.Zg=class extends self.ua{constructor(f,a){super(f,a);this.ba=new Map;this.Uc=!0;K(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ba.get(b);this.Uc&&d.parentElement.removeChild(d);this.ba.delete(b)}}],["set-visible",b=>{this.Uc&&(this.ba.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Uc){var d=this.ba.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ba.get(b.elementId);throw Error("required override");}],["focus",b=>this.Oc(b)],["set-css-style",b=>{this.ba.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ba.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ba.get(b.elementId).removeAttribute(b.name)}]]);O(this,b=>b)}Oc(f){var a=this.ba.get(f.elementId);f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function d(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Pg?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=m.Tg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let g=!1,n=!1;function q(){if(!g){try{new Worker("blob://",{get type(){n=
!0}})}catch(m){}g=!0}return n}let w=new Audio;const B={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;async function D(m){m=await x(m);return(new TextDecoder("utf-8")).decode(m)}
function x(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const y=[];let C=0;window.RealFile=window.File;const E=[],A=new Map,F=new Map;let J=0;const L=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");L.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.fa=class m{constructor(c){this.ca=c.Vg;this.ra=null;this.F="";this.ic=c.Sg;
this.yb={};this.Ma=this.xb=null;this.Sb=[];this.lb=this.G=this.Ra=null;this.Qa=-1;this.Jg=()=>this.Pf();this.Pa=[];this.s=c.me;this.jb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&q()||(this.ca=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.ca=!1;if("cordova"===this.s&&this.ca)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Yb=this.ja=null;"html5"!==
this.s&&"playable-ad"!==this.s||!this.jb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.s||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.zf(k));this.C("runtime",
"create-job-worker",()=>this.Af());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Gd(c)):this.Gd(c)}f(){this.Ac();this.ra&&(this.ra=this.ra.onmessage=null);this.xb&&(this.xb.terminate(),this.xb=null);this.Ma&&(this.Ma.f(),this.Ma=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}Ne(){return f&&"cordova"===this.s}tc(){const c=navigator.userAgent;return f&&e.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}Le(){return a}vd(){return a&&e.has(this.s)}async Gd(c){"macos-wkwebview"===
this.s&&this.Sc({type:"ready"});if("playable-ad"===this.s){this.ja=self.c3_base64files;this.Yb={};await this.ff();for(let l=0,p=c.Ua.length;l<p;++l){var k=c.Ua[l].toLowerCase();this.Yb.hasOwnProperty(k)?c.Ua[l]={Pg:!0,Tg:this.Yb[k]}:this.ja.hasOwnProperty(k)&&(c.Ua[l]=URL.createObjectURL(this.ja[k]))}}c.Kg?this.F=c.Kg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Xg&&(this.yb=c.Xg);k=new MessageChannel;this.ra=
k.port1;this.ra.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Lf(l));this.lb=new self.Oe(this);await P(this.lb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.uf(c,k.port2):await this.tf(c,k.port2)}Dc(c){c=this.yb.hasOwnProperty(c)?this.yb[c]:c.endsWith("/workermain.js")&&this.yb.hasOwnProperty("workermain.js")?
this.yb["workermain.js"]:"playable-ad"===this.s&&this.ja.hasOwnProperty(c.toLowerCase())?this.ja[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async nc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.jb)return c=await this.zb(l.Og?c:this.ic+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");
c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}pa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}Fd(c){var k=this.lb;return{baseUrl:this.F,windowInnerWidth:this.pa(),windowInnerHeight:this.ga(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Xa(),projectData:c.eh,previewImageBlobs:window.cr_previewImageBlobs||this.ja,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.bh||"",exportType:c.me,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.dh,jobScheduler:{inputPort:k.ad,outputPort:k.gd,maxNumWorkers:k.Gg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ic+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ic+"opus.wasm.wasm",isFileProtocol:this.jb,isiOSCordova:this.Ne(),isiOSWebView:this.tc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async uf(c,k){var l=this.Dc(c.Wg);this.xb=
await this.nc(l,this.F,{type:"module",name:"Runtime",Og:!0});this.G=document.createElement("canvas");this.G.style.display="none";l=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;let p=c.nd||[],v=c.Ua;p=await Promise.all(p.map(r=>this.Ha(r)));v=await Promise.all(v.map(r=>this.Ha(r)));if("cordova"===this.s)for(let r=0,t=c.lc.length;r<t;++r){const z=c.lc[r],G=z[0];if(G===c.ld||"scriptsInEvents.js"===G||G.endsWith("/scriptsInEvents.js"))z[1]=await this.Ha(G)}this.xb.postMessage(Object.assign(this.Fd(c),
{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:v,projectScripts:c.lc,mainProjectScript:c.ld,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...Q(this.lb)]);this.Sb=E.map(r=>new r(this));this.Ed();self.c3_callFunction=(r,t)=>this.Ra.vf(r,t);"preview"===this.s&&(self.goToLastErrorScript=()=>this.uc("runtime","go-to-last-error-script"))}async tf(c,k){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);
window.c3canvas=this.G;this.Sb=E.map(r=>new r(this));this.Ed();var l=c.Ua.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.nd)&&l.unshift(...c.nd);l=await Promise.all(l.map(r=>this.Ha(r)));await Promise.all(l.map(r=>d(r)));l=self.C3_ProjectScriptsStatus;const p=c.ld,v=c.lc;for(let [r,t]of v)if(t||(t=r),r===p)try{t=await this.Ha(t),await d(t),"preview"!==this.s||l[r]||this.Od(r,"main script did not run to completion")}catch(z){this.Od(r,z)}else if("scriptsInEvents.js"===
r||r.endsWith("/scriptsInEvents.js"))t=await this.Ha(t),await d(t);"preview"===this.s&&"object"!==typeof self.Yg.$g?(this.Lb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Fd(c),{isInWorker:!1,messagePort:k,canvas:this.G,runOnStartupFunctions:L}),this.Id(),this.Ma=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ma,
c))}Od(c,k){this.Lb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Id(){this.Lb()}Lb(){const c=window.Lg;c&&(c.parentElement.removeChild(c),window.Lg=null)}async Af(){const c=await R(this.lb);return{outputPort:c,transferables:[c]}}rf(){if(this.ca)throw Error("not available in worker mode");return this.Ma}uc(c,k,l,p,v){this.ra.postMessage({type:"event",
component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},v)}xd(c,k,l,p,v){const r=J++,t=new Promise((z,G)=>{F.set(r,{resolve:z,reject:G})});this.ra.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},v);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Ff(c);if("result"===k)this.Sf(c);else if("runtime-ready"===k)this.Tf();else if("alert-error"===k)this.Lb(),alert(c.message);else if("creating-runtime"===k)this.Id();else throw Error(`unknown message '${k}'`);
}Ff(c){const k=c.component,l=c.handler,p=c.data,v=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==v&&this.Kb(v,!1,""+t);return}if(null===v)return r;r&&r.then?r.then(t=>this.Kb(v,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Kb(v,!1,""+t)}):this.Kb(v,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Kb(c,
k,l){let p;l&&l.transferables&&(p=l.transferables);this.ra.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}Sf(c){const k=c.responseId,l=c.isOk;c=c.result;const p=F.get(k);l?p.resolve(c):p.reject(c);F.delete(k)}C(c,k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static Da(c){if(E.includes(c))throw Error("DOM handler already added");E.push(c)}Ed(){for(const c of this.Sb)if("runtime"===c.cb){this.Ra=c;return}throw Error("cannot find runtime DOM handler");
}Lf(c){this.uc("debugger","message",c)}Tf(){for(const c of this.Sb)c.od()}static Xa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||h)}static Mb(c){h=!!c}af(c){this.Pa.push(c);this.Rc()}eg(c){c=this.Pa.indexOf(c);if(-1===c)throw Error("invalid callback");this.Pa.splice(c,1);this.Pa.length||this.Ac()}Rc(){-1===this.Qa&&this.Pa.length&&(this.Qa=requestAnimationFrame(this.Jg))}Ac(){-1!==this.Qa&&(cancelAnimationFrame(this.Qa),this.Qa=-1)}Pf(){this.Qa=
-1;for(const c of this.Pa)c();this.Rc()}xa(c){this.Ra.xa(c)}Fa(c){this.Ra.Fa(c)}Qc(){this.Ra.Qc()}Fb(c){this.Ra.Fb(c)}Me(){return!!B["audio/webm; codecs=opus"]}async Cg(c){c=await this.xd("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Ke(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}wd(c){return!this.Ke(c)}async Ha(c){return"cordova"===this.s&&(c.startsWith("file:")||this.jb&&this.wd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),
c=await this.zb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async zf(c){const k=c.filename;switch(c.as){case "text":return await this.De(k);case "buffer":return await this.zb(k);default:throw Error("unsupported type");}}rd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,v=>{v.file(l,p)},p)})}async De(c){c=await this.rd(c);return await D(c)}Bc(){if(y.length&&!(8<=C)){C++;var c=y.shift();
this.gf(c.filename,c.Ug,c.Ng)}}zb(c){return new Promise((k,l)=>{y.push({filename:c,Ug:p=>{C--;this.Bc();k(p)},Ng:p=>{C--;this.Bc();l(p)}});this.Bc()})}async gf(c,k,l){try{const p=await this.rd(c),v=await x(p);k(v)}catch(p){l(p)}}Sc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async ff(){const c=[];for(const [k,
l]of Object.entries(this.ja))c.push(this.ef(k,l));await Promise.all(c)}async ef(c,k){if("object"===typeof k)this.ja[c]=new Blob([k.str],{type:k.type}),this.Yb[c]=k.str;else{let l=await this.pf(k);l||(l=this.jf(k));this.ja[c]=l}}async pf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}jf(c){c=this.Zf(c);return this.df(c.data,c.Qg)}Zf(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{Qg:c,data:l}}df(c,k){var l=c.length;let p=l>>2,v=new Uint8Array(l),r=new Uint32Array(v.buffer,0,p),t,z;for(z=t=0;t<p;++t)r[t]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=
3;l--;)v[z]=c.charCodeAt(z),++z;return new Blob([v],{type:k})}}}"use strict";
{const f=self.fa;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function w(e){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await w(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function x(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await D(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function y(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),E=new Set(["canvas","body","html"]);function A(e){E.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function F(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,c,k){e=await x(e,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let J=!1;document.addEventListener("pause",()=>J=!0);document.addEventListener("resume",()=>J=!1);function L(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Da(class extends self.ua{constructor(e){super(e,"runtime");this.Yd=!0;this.Sa=-1;this.jd="any";this.Pd=this.Qd=!1;this.La=
this.tb=this.za=null;this.dc=this.cc=0;this.be=e.pa();this.Wb=e.ga();this.vb=0;e.C("canvas","update-size",c=>this.Wf(c));e.C("runtime","invoke-download",c=>this.Jf(c));e.C("runtime","raster-svg-image",c=>this.Qf(c));e.C("runtime","get-svg-image-size",c=>this.Hf(c));e.C("runtime","set-target-orientation",c=>this.Uf(c));e.C("runtime","register-sw",()=>this.Rf());e.C("runtime","post-to-debugger",c=>this.Kd(c));e.C("runtime","go-to-script",c=>this.Kd(c));e.C("runtime","before-start-ticking",()=>this.yf());
e.C("runtime","debug-highlight",c=>this.Bf(c));e.C("runtime","enable-device-orientation",()=>this.cf());e.C("runtime","enable-device-motion",()=>this.bf());e.C("runtime","add-stylesheet",c=>this.xf(c));e.C("runtime","alert",c=>this.Hc(c));e.C("runtime","hide-cordova-splash",()=>this.If());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||y(k)||c.preventDefault()});const m=e.G;window.addEventListener("selectstart",
A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.qb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,
{passive:!1});window.addEventListener("resize",()=>this.Xf());window.addEventListener("fullscreenchange",()=>this.Za());window.addEventListener("webkitfullscreenchange",()=>this.Za());window.addEventListener("mozfullscreenchange",()=>this.Za());window.addEventListener("fullscreenerror",c=>this.Kc(c));window.addEventListener("webkitfullscreenerror",c=>this.Kc(c));window.addEventListener("mozfullscreenerror",c=>this.Kc(c));e.tc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;
if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):y(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.Yf(c);this.Na=new Set;this.Zb=new WeakSet;this.qa=!1}yf(){"cordova"===this.u.s?(document.addEventListener("pause",()=>this.Pc(!0)),document.addEventListener("resume",()=>this.Pc(!1))):document.addEventListener("visibilitychange",()=>this.Pc(document.hidden));
return{isSuspended:!(!document.hidden&&!J)}}od(){window.addEventListener("focus",()=>this.ab("window-focus"));window.addEventListener("blur",()=>{this.ab("window-blur",{parentHasFocus:L()});this.qb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||y(h))&&this.ab("keyboard-blur")});window.addEventListener("keydown",h=>this.Jd("keydown",h));window.addEventListener("keyup",h=>this.Jd("keyup",h));window.addEventListener("dblclick",h=>this.Mc("dblclick",h,d));window.addEventListener("wheel",
h=>this.Nf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.Ec(h);this.$a("pointerdown",h)}),this.u.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.tb=new self.Se(()=>this.mf(),5),this.tb.Td=!0,window.addEventListener("pointerrawupdate",h=>this.Of(h))):window.addEventListener("pointermove",h=>this.$a("pointermove",h)),window.addEventListener("pointerup",h=>this.$a("pointerup",h)),window.addEventListener("pointercancel",h=>this.$a("pointercancel",
h))):(window.addEventListener("mousedown",h=>{this.Ec(h);this.Nc("pointerdown",h)}),window.addEventListener("mousemove",h=>this.Nc("pointermove",h)),window.addEventListener("mouseup",h=>this.Nc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Ec(h);this.Jb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Jb("pointermove",h)),window.addEventListener("touchend",h=>this.Jb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Jb("pointercancel",h)));const e=()=>this.Qc();
window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0);this.u.Le()&&!this.u.vd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Ic(this.ga(),navigator.virtualKeyboard.boundingRect.height)}))}Ic(e,h){document.body.style.transform="";if(0<h){var m=document.activeElement;
m&&(m=m.getBoundingClientRect(),e=(m.top+m.bottom)/2-(e-h)/2,e>h&&(e=h),0>e&&(e=0),0<e&&(document.body.style.transform=`translateY(${-e}px)`))}}ab(e,h){u(this,e,h||null,n)}pa(){return this.u.pa()}ga(){return this.u.ga()}Xf(){const e=this.pa(),h=this.ga();if(this.u.vd()){if(this.be===e&&h<this.Wb){this.vb=this.Wb-h;this.Ic(this.Wb,this.vb);return}0<this.vb&&(this.vb=0,this.Ic(h,this.vb));this.be=e;this.Wb=h}this.ab("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,
isFullscreen:f.Xa()});this.u.tc()&&(-1!==this.Sa&&clearTimeout(this.Sa),this.Ld(e,h,0))}fg(e,h,m){-1!==this.Sa&&clearTimeout(this.Sa);this.Sa=setTimeout(()=>this.Ld(e,h,m),48)}Ld(e,h,m){const c=this.pa(),k=this.ga();this.Sa=-1;c!=e||k!=h?this.ab("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Xa()}):10>m&&this.fg(c,k,m+1)}Uf(e){this.jd=e.targetOrientation}yg(){const e=this.jd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>
console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Za(){const e=f.Xa();e&&"any"!==this.jd&&this.yg();u(this,"fullscreenchange",
{isFullscreen:e,innerWidth:this.pa(),innerHeight:this.ga()})}Kc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);u(this,"fullscreenerror",{isFullscreen:f.Xa(),innerWidth:this.pa(),innerHeight:this.ga()})}Pc(e){e?this.u.Ac():this.u.Rc();u(this,"visibilitychange",{hidden:e})}Jd(e,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;H(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},
d)}Nf(e){u(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Mc(e,h,m){a(h)||H(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},m)}Nc(e,h){if(!a(h)){var m=this.qb;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");
H(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.qb=h.buttons;this.Mc(h.type,h,g)}}$a(e,h){if(this.tb&&"pointermove"!==e){var m=this.tb;m.ib||(N(m),m.Vb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.qb);H(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,
button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:(h.movementX||0)+this.cc,movementY:(h.movementY||0)+this.dc,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);this.dc=this.cc=0;"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Mc(m,h,g),this.qb=
h.buttons)}Of(e){this.La&&(this.cc+=this.La.movementX||0,this.dc+=this.La.movementY||0);this.La=e;e=this.tb;if(-1===e.Ta){var h=Date.now(),m=h-e.Vb,c=e.Eg;m>=c&&e.Td?(e.Vb=h,e.ib=!0,e.Vc(),e.ib=!1):e.Ta=self.setTimeout(e.le,Math.max(c-m,4))}}mf(){this.$a("pointermove",this.La);this.La=null}Jb(e,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];H(this,e,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,
pageY:k.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}Ec(e){window!==window.top&&window.focus();this.Hd(e.target)&&document.activeElement&&!this.Hd(document.activeElement)&&document.activeElement.blur()}Hd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}cf(){this.Qd||
(this.Qd=!0,window.addEventListener("deviceorientation",e=>this.Df(e)),window.addEventListener("deviceorientationabsolute",e=>this.Ef(e)))}bf(){this.Pd||(this.Pd=!0,window.addEventListener("devicemotion",e=>this.Cf(e)))}Df(e){u(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}Ef(e){u(this,"deviceorientationabsolute",{absolute:!!e.absolute,
alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}Cf(e){let h=null;var m=e.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});u(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},d)}Wf(e){const h=this.u.G;h.style.width=e.styleWidth+"px";
h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Yd&&(h.style.display="",this.Yd=!1)}Jf(e){const h=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=h;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async Qf(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);h=h?await createImageBitmap(e,h):await createImageBitmap(e);
return{imageBitmap:h,transferables:[h]}}async Hf(e){return await self.C3_GetSvgImageSize(e.blob)}async xf(e){await q(e.url)}Qc(){var e=[...this.Na];this.Na.clear();if(!this.qa)for(const h of e)(e=h.play())&&e.catch(()=>{this.Zb.has(h)||this.Na.add(h)})}xa(e){if("function"!==typeof e.play)throw Error("missing play function");this.Zb.delete(e);let h;try{h=e.play()}catch(m){this.Na.add(e);return}h&&h.catch(()=>{this.Zb.has(e)||this.Na.add(e)})}Fa(e){this.Na.delete(e);this.Zb.add(e)}Fb(e){this.qa=!!e}If(){navigator.splashscreen&&
navigator.splashscreen.hide&&navigator.splashscreen.hide()}Bf(e){if(e.show){this.za||(this.za=document.createElement("div"),this.za.id="inspectOutline",document.body.appendChild(this.za));var h=this.za;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.za&&(this.za.style.display="none")}Rf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Kd(e){window.c3_postToMessagePort&&(e.from="runtime",
window.c3_postToMessagePort(e))}vf(e,h){return this.u.xd(this.cb,"js-invoke-function",{name:e,params:h},void 0,void 0)}Hc(e){alert(e.message)}Yf(e){"entered-fullscreen"===e?(f.Mb(!0),this.Za()):"exited-fullscreen"===e?(f.Mb(!1),this.Za()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function P(f){if(f.Dg)throw Error("already initialised");f.Dg=!0;var a=f.hc.Dc("dispatchworker.js");f.Xc=await f.hc.nc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.ad=a.port1;f.Xc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.gd=await R(f)}function Q(f){return[f.ad,f.gd]}
async function R(f){const a=f.Zd.length;var b=f.hc.Dc("jobworker.js");b=await f.hc.nc(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;f.Xc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);f.Zd.push(b);return g.port1}
self.Oe=class{constructor(f){this.hc=f;this.F=f.F;this.F="preview"===f.s?this.F+"workers/":this.F+f.ic;this.Gg=Math.min(navigator.hardwareConcurrency||2,16);this.Xc=null;this.Zd=[];this.gd=this.ad=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.fa({Vg:!1,Wg:"workermain.js",Ua:["scripts/c3runtime.js"],lc:[],ld:"",Sg:"scripts/",nd:[],me:"html5"}));"use strict";
{const f=180/Math.PI;self.da=class extends self.ua{constructor(a){super(a,"audio");this.Rb=this.c=null;this.Tb=this.$c=!1;this.ta=()=>this.zg();this.$=[];this.D=[];this.ia=null;this.$d="";this.ae=-1;this.sb=new Map;this.dd=1;this.qa=!1;this.kd=0;this.jc=1;this.Yc=0;this.de="HRTF";this.Ud="inverse";this.ee=600;this.ce=1E4;this.ge=1;this.Wd=this.hd=!1;this.je=this.u.Me();this.aa=new Map;this.Ja=new Set;this.bd=!1;this.ed="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Mf(b,d);this.Qb=null;
self.C3Audio_GetOutputStream=()=>this.Gf();self.C3Audio_DOMInterface=this;K(this,[["create-audio-context",b=>this.hf(b)],["play",b=>this.$f(b)],["stop",b=>this.wg(b)],["stop-all",()=>this.xg()],["set-paused",b=>this.pg(b)],["set-volume",b=>this.ug(b)],["fade-volume",b=>this.nf(b)],["set-master-volume",b=>this.ng(b)],["set-muted",b=>this.og(b)],["set-silent",b=>this.rg(b)],["set-looping",b=>this.mg(b)],["set-playback-rate",b=>this.qg(b)],["seek",b=>this.gg(b)],["preload",b=>this.ag(b)],["unload",b=>
this.Ag(b)],["unload-all",()=>this.Bg()],["set-suspended",b=>this.sg(b)],["get-suspended",()=>this.sf()],["add-effect",b=>this.Cd(b)],["set-effect-param",b=>this.jg(b)],["remove-effects",b=>this.cg(b)],["tick",b=>this.Vf(b)],["load-state",b=>this.Kf(b)]])}async hf(a){a.isiOSCordova&&(this.hd=!0);this.kd=a.timeScaleMode;this.de=["equalpower","HRTF","soundfield"][a.panningModel];this.Ud=["linear","inverse","exponential"][a.distanceModel];this.ee=a.refDistance;this.ce=a.maxDistance;this.ge=a.rolloffFactor;
var b={latencyHint:a.latencyHint};this.je||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.c=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.c=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Dd();this.c.onstatechange=()=>{"running"!==this.c.state&&this.Dd()};this.Rb=this.c.createGain();this.Rb.connect(this.c.destination);b=a.listenerPos;this.c.listener.setPosition(b[0],b[1],b[2]);this.c.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=
()=>this.oc();try{await Promise.all(a.preloadList.map(d=>this.Hb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.c.sampleRate}}Dd(){this.Tb||(this.$c=!1,window.addEventListener("pointerup",this.ta,!0),window.addEventListener("touchend",this.ta,!0),window.addEventListener("click",this.ta,!0),window.addEventListener("keydown",this.ta,!0),this.Tb=!0)}kf(){this.Tb&&(this.$c=!0,window.removeEventListener("pointerup",this.ta,!0),
window.removeEventListener("touchend",this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",this.ta,!0),this.Tb=!1)}zg(){if(!this.$c){var a=this.c;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.kf()}}W(){return this.c}oc(){return this.c.currentTime}va(){return this.Rb}td(a){return(a=this.aa.get(a.toLowerCase()))?a[0].P():this.va()}ne(a,
b){a=a.toLowerCase();let d=this.aa.get(a);d||(d=[],this.aa.set(a,d));b.lg(d.length);b.tg(a);d.push(b);this.Nd(a)}Nd(a){let b=this.va();const d=this.aa.get(a);if(d&&d.length){b=d[0].P();for(let g=0,n=d.length;g<n;++g){const q=d[g];g+1===n?q.S(this.va()):q.S(d[g+1].P())}}for(const g of this.na(a))g.Te(b);this.Aa&&this.ed===a&&(this.Aa.disconnect(),this.Aa.connect(b))}Bb(){return this.dd}Cb(){return this.qa}kg(){this.Wd=!0}Fe(a,b){return b?this.u.Cg(a).then(d=>{const g=this.c.createBuffer(1,d.length,
48E3);g.getChannelData(0).set(d);return g}):new Promise((d,g)=>{this.c.decodeAudioData(a,d,g)})}xa(a){this.u.xa(a)}Fa(a){this.u.Fa(a)}yd(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.f():++b}this.D.length=b}Ue(){let a=0;for(let b=0,d=this.$.length;b<d;++b){const g=this.$[b];this.$[a]=g;g.wa()?g.f():++a}this.$.length=a}*na(a){if(a)for(const b of this.D)self.da.Ge(b.Y,a)&&(yield b);else this.ia&&!this.ia.T()&&(yield this.ia)}async Hb(a,b,d,g,n){for(const q of this.$)if(q.Wa()===
b)return await S(q),q;if(n)return null;g&&(this.hd||this.Wd)&&this.Ue();n="audio/webm; codecs=opus"===d&&!this.je;g&&n&&this.kg();a=!g||this.hd||n?new self.Be(this,a,b,d,g,n):new self.ze(this,a,b,d,g);this.$.push(a);await S(a);return a}async Cc(a,b,d,g,n){for(const q of this.D)if(q.Wa()===b&&(q.mc()||n))return q.We(g),q;a=await this.Hb(a,b,d,n);g="html5"===a.Tc?new self.Ae(a.i,a,g):new self.Ce(a.i,a,g);this.D.push(g);return g}$e(a){let b=this.sb.get(a);if(!b){let d=null;b={md:0,Rg:new Promise(g=>
d=g),resolve:d};this.sb.set(a,b)}b.md++}dg(a){const b=this.sb.get(a);if(!b)throw Error("expected pending tag");b.md--;0===b.md&&(b.resolve(),this.sb.delete(a))}zc(a){a||(a=this.$d);return(a=this.sb.get(a))?a.Rg:Promise.resolve()}Ib(){if(0<this.Ja.size)M(this);else for(const a of this.D)if(a.ud()){M(this);break}}Ga(){for(var a of this.Ja)a.Ga();a=this.oc();for(var b of this.D)b.Ga(a);b=this.D.filter(d=>d.ud()).map(d=>d.Va());u(this,"state",{tickCount:this.ae,audioInstances:b,analysers:[...this.Ja].map(d=>
d.Ie())});0===b.length&&0===this.Ja.size&&this.Ub&&(this.u.eg(this.ke),this.Ub=!1)}vc(a,b,d){u(this,"trigger",{type:a,tag:b,aiid:d})}async $f(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,q=a.tag,w=a.isLooping,B=a.vol,D=a.pos,x=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.c.getOutputTimestamp?(a=this.c.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.c.currentTime);this.$d=q;this.$e(q);try{this.ia=await this.Cc(b,d,g,q,n),x?(this.ia.Eb(!0),this.ia.Ve(x.x,
x.y,x.angle,x.innerAngle,x.outerAngle,x.outerGain),x.hasOwnProperty("uid")&&this.ia.Xe(x.uid)):this.ia.Eb(!1),this.ia.Play(w,B,D,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.dg(q)}M(this)}wg(a){a=a.tag;for(const b of this.na(a))b.oa()}xg(){for(const a of this.D)a.oa()}pg(a){const b=a.tag;a=a.paused;for(const d of this.na(b))a?d.Ya():d.Db();this.Ib()}ug(a){const b=a.tag;a=a.vol;for(const d of this.na(b))d.Gb(a)}async nf(a){const b=a.tag,d=a.vol,
g=a.duration;a=a.stopOnEnd;await this.zc(b);for(const n of this.na(b))n.He(d,g,a);this.Ib()}ng(a){this.dd=a.vol;for(const b of this.D)b.Ob()}og(a){const b=a.tag;a=a.isMuted;for(const d of this.na(b))d.zd(a)}rg(a){this.qa=a.isSilent;this.u.Fb(this.qa);for(const b of this.D)b.Nb()}mg(a){const b=a.tag;a=a.isLooping;for(const d of this.na(b))d.xc(a)}async qg(a){const b=a.tag;a=a.rate;await this.zc(b);for(const d of this.na(b))d.Bd(a)}async gg(a){const b=a.tag;a=a.pos;await this.zc(b);for(const d of this.na(b))d.wc(a)}async ag(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.Cc(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async Ag(a){if(a=await this.Hb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.$.indexOf(a),-1!==a&&this.$.splice(a,1)}Bg(){for(const a of this.$)a.f();this.$.length=0}sg(a){a=a.isSuspended;!a&&this.c.resume&&this.c.resume();for(const b of this.D)b.yc(a);a&&this.c.suspend&&this.c.suspend()}sf(){return this.c?this.c.state:"suspended"}Vf(a){this.jc=a.timeScale;this.Yc=
a.gameTime;this.ae=a.tickCount;if(0!==this.kd)for(var b of this.D)b.Ia();(b=a.listenerPos)&&this.c.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.ha===a&&g.Ad(d.x,d.y,d.angle)}}async Cd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.te(this,...g);else if("delay"===b)g=new self.re(this,...g);else if("convolution"===b){b=null;try{b=await this.Hb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}g=new self.qe(this,b.Z,...g);g.hg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.ue(this,...g);else if("phaser"===b)g=new self.we(this,...g);else if("gain"===b)g=new self.ve(this,...g);else if("tremolo"===b)g=new self.ye(this,...g);else if("ringmod"===b)g=new self.xe(this,...g);else if("distortion"===b)g=new self.se(this,...g);else if("compressor"===b)g=new self.pe(this,...g);else if("analyser"===b)g=new self.oe(this,...g);else throw Error("invalid effect type");this.ne(d,
g);this.Md()}jg(a){const b=a.index,d=a.param,g=a.value,n=a.ramp,q=a.time;a=this.aa.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,n,q),this.Md())}cg(a){a=a.tag.toLowerCase();const b=this.aa.get(a);if(b&&b.length){for(const d of b)d.f();this.aa.delete(a);this.Nd(a)}}Ze(a){this.Ja.add(a);this.Ib()}bg(a){this.Ja.delete(a)}Md(){this.bd||(this.bd=!0,Promise.resolve().then(()=>this.lf()))}lf(){const a={};for(const [b,d]of this.aa)a[b]=d.map(g=>g.Va());u(this,"fxstate",{fxstate:a});this.bd=!1}async Kf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.wa()&&1===b||(d.wa()||2!==b)&&d.oa();for(const g of this.aa.values())for(const n of g)n.f();this.aa.clear();this.jc=a.timeScale;this.Yc=a.gameTime;d=a.listenerPos;this.c.listener.setPosition(d[0],d[1],d[2]);this.qa=a.isSilent;this.u.Fb(this.qa);this.dd=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.Cd(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.wf(g,b)));this.Ib()}async wf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,q=a.isMusic,w=a.tag,B=a.isLooping,D=a.volume,x=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.Cc(d,g,n,w,q)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.Re(a.pan);b.Play(B,D,x,0);a.isPlaying||b.Ya();b.Gc(a)}}}Mf(a,b){this.Aa&&this.Aa.disconnect();this.ed=b.toLowerCase();this.Aa=this.c.createMediaStreamSource(a);this.Aa.connect(this.td(this.ed))}Gf(){this.Qb||(this.Qb=this.c.createMediaStreamDestination(),
this.Rb.connect(this.Qb));return this.Qb.stream}static Ge(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ye(a){return a*f}static Ee(a){return Math.pow(10,a/20)}static sd(a){return Math.max(Math.min(self.da.Ee(a),1),0)}static Qe(a){return Math.log(a)/Math.log(10)*20}static Pe(a){return self.da.Qe(Math.max(Math.min(a,1),0))}static Mg(a,b){return 1-Math.exp(-b*a)}};self.fa.Da(self.da)}"use strict";function S(f){f.Xb||(f.Xb=f.Fc());return f.Xb}
self.pd=class{constructor(f,a,b,d,g){this.i=f;this.Ig=a;this.Ca=b;this.R=d;this.Fg=g;this.Tc="";this.Xb=null}f(){this.Xb=this.i=null}Fc(){}W(){return this.i.W()}qc(){return this.Ig}Wa(){return this.Ca}pc(){return this.R}wa(){return this.Fg}ea(){}};"use strict";
self.ze=class extends self.pd{constructor(f,a,b,d,g){super(f,a,b,d,g);this.Tc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.mb=this.nb=null;this.K.addEventListener("canplaythrough",()=>!0);this.rb=this.W().createGain();this.pb=null;this.K.addEventListener("canplay",()=>{this.nb&&(this.nb(),this.mb=this.nb=null);!this.pb&&this.K&&(this.pb=this.W().createMediaElementSource(this.K),this.pb.connect(this.rb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Ca}' error: `,n);this.mb&&(this.mb(n),this.mb=this.nb=null)})}f(){this.i.yd(this);this.rb.disconnect();this.rb=null;this.pb.disconnect();this.pb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.f()}Fc(){return new Promise((f,a)=>{this.nb=f;this.mb=a;this.K.src=this.Ca})}O(){return this.K}ea(){return this.K.duration}};"use strict";
async function T(f){if(f.ya)return f.ya;var a=f.i.u;if("cordova"===a.s&&a.wd(f.Ca)&&a.jb)f.ya=await a.zb(f.Ca);else{a=await fetch(f.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.ya=await a.arrayBuffer()}}async function U(f){if(f.Z)return f.Z;f.Z=await f.i.Fe(f.ya,f.Hg);f.ya=null}
self.Be=class extends self.pd{constructor(f,a,b,d,g,n){super(f,a,b,d,g);this.Tc="webaudio";this.Z=this.ya=null;this.Hg=!!n}f(){this.i.yd(this);this.Z=this.ya=null;super.f()}async Fc(){try{await T(this),await U(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Ca}': `,f)}}ea(){return this.Z?this.Z.duration:0}};"use strict";
{let f=0;self.qd=class{constructor(a,b,d){this.i=a;this.L=b;this.Y=d;this.Pb=f++;this.M=this.W().createGain();this.M.connect(this.va());this.B=null;this.kb=!1;this.la=[0,0,0];this.ka=[0,0,0];this.I=!0;this.V=this.ma=this.H=!1;this.wb=1;this.Ka=!1;this.sa=1;a=this.i.kd;this.cd=1===a&&!this.wa()||2===a;this.gb=this.ha=-1;this.ie=!1}f(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}va(){return this.i.td(this.Y)}Bb(){return this.i.Bb()}Ab(){return this.cd?
this.i.Yc:performance.now()/1E3}qc(){return this.L.qc()}Wa(){return this.L.Wa()}pc(){return this.L.pc()}wa(){return this.L.wa()}We(a){this.Y=a}T(){}mc(){}IsPlaying(){return!this.I&&!this.H&&!this.T()}ud(){return!this.I&&!this.T()}Ea(){}ea(){return this.L.ea()}Play(){}oa(){}Ya(){}Db(){}Gb(a){this.wb=a;this.M.gain.cancelScheduledValues(0);this.gb=-1;this.M.gain.value=this.rc()}He(a,b,d){if(!this.Ka){a*=this.Bb();var g=this.M.gain;g.cancelScheduledValues(0);var n=this.i.oc();b=n+b;g.setValueAtTime(g.value,
n);g.linearRampToValueAtTime(a,b);this.wb=a;this.gb=b;this.ie=d}}Ob(){this.Gb(this.wb)}Ga(a){-1!==this.gb&&a>=this.gb&&(this.gb=-1,this.ie&&this.oa(),this.i.vc("fade-ended",this.Y,this.Pb))}rc(){const a=this.wb*this.Bb();return isFinite(a)?a:0}zd(a){a=!!a;this.Ka!==a&&(this.Ka=a,this.Nb())}Cb(){return this.i.Cb()}Nb(){}xc(){}Bd(a){this.sa!==a&&(this.sa=a,this.Ia())}Ia(){}wc(){}yc(){}Eb(a){a=!!a;this.kb!==a&&((this.kb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.de,this.B.distanceModel=
this.i.Ud,this.B.refDistance=this.i.ee,this.B.maxDistance=this.i.ce,this.B.rolloffFactor=this.i.ge),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.va())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.va())))}Ve(a,b,d,g,n,q){this.kb&&(this.Ad(a,b,d),a=self.da.Ye,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}Ad(a,b,d){this.kb&&(this.la[0]=a,this.la[1]=b,this.la[2]=0,this.ka[0]=Math.cos(d),this.ka[1]=Math.sin(d),this.ka[2]=0,this.B.setPosition(...this.la),
this.B.setOrientation(...this.ka))}Xe(a){this.ha=a}sc(){}Te(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Va(){return{aiid:this.Pb,tag:this.Y,duration:this.ea(),volume:this.wb,isPlaying:this.IsPlaying(),playbackTime:this.Ea(),playbackRate:this.sa,uid:this.ha,bufferOriginalUrl:this.qc(),bufferUrl:"",bufferType:this.pc(),isMusic:this.wa(),isLooping:this.V,isMuted:this.Ka,resumePosition:this.sc(),pan:this.Je()}}Gc(a){this.Bd(a.playbackRate);this.zd(a.isMuted)}Je(){if(!this.B)return null;const a=
this.B;return{pos:this.la,orient:this.ka,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ha}}Re(a){if(a){this.Eb(!0);a=this.B;var b=a.pos;this.la[0]=b[0];this.la[1]=b[1];this.la[2]=b[2];b=a.orient;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];a.setPosition(...this.la);a.setOrientation(...this.ka);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ha=a.uid}else this.Eb(!1)}}}"use strict";
self.Ae=class extends self.qd{constructor(f,a,b){super(f,a,b);this.L.rb.connect(this.M);this.L.onended=()=>this.Jc()}f(){this.oa();this.L.rb.disconnect();super.f()}O(){return this.L.O()}Jc(){this.I=!0;this.ha=-1;this.i.vc("ended",this.Y,this.Pb)}T(){return this.O().ended}mc(){return this.I?!0:this.T()}Ea(){let f=this.O().currentTime;this.V||(f=Math.min(f,this.ea()));return f}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Gb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Wa()}' to position '${b}': `,g)}this.i.xa(d);this.H=this.I=!1;this.V=f;this.sa=1}oa(){const f=this.O();f.paused||f.pause();this.i.Fa(f);this.I=!0;this.H=!1;this.ha=-1}Ya(){if(!(this.H||this.I||this.T())){var f=this.O();f.paused||f.pause();this.i.Fa(f);this.H=!0}}Db(){!this.H||this.I||this.T()||(this.i.xa(this.O()),this.H=!1)}Nb(){this.O().muted=this.Ka||this.Cb()}xc(f){f=!!f;this.V!==f&&
(this.V=f,this.O().loop=f)}Ia(){let f=this.sa;this.cd&&(f*=this.i.jc);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}wc(f){if(!this.I&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}sc(){return this.Ea()}yc(f){f?this.IsPlaying()?(this.O().pause(),this.ma=!0):this.ma=!1:this.ma&&(this.i.xa(this.O()),this.ma=!1)}};"use strict";
function V(f){f.j&&f.j.disconnect();f.j=null;f.bb=null}
self.Ce=class extends self.qd{constructor(f,a,b){super(f,a,b);this.j=null;this.$b=d=>this.Jc(d);this.Zc=!0;this.bb=null;this.N=this.ac=this.bc=0;this.fd=1}f(){this.oa();V(this);this.$b=null;super.f()}Jc(f){this.H||this.ma||f.target!==this.bb||(this.I=this.Zc=!0,this.ha=-1,V(this),this.i.vc("ended",this.Y,this.Pb))}T(){return!this.I&&this.j&&this.j.loop||this.H?!1:this.Zc}mc(){return!this.j||this.I?!0:this.T()}Ea(){let f;f=this.H?this.N:this.ac+(this.Ab()-this.bc)*this.sa;this.V||(f=Math.min(f,this.ea()));
return f}Play(f,a,b,d){this.fd=1;this.Gb(a);V(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.Z;this.j.connect(this.M);this.bb=this.j;this.j.onended=this.$b;this.j.loop=f;this.j.start(d,b);this.H=this.I=this.Zc=!1;this.V=f;this.sa=1;this.bc=this.Ab();this.ac=b}oa(){if(this.j)try{this.j.stop(0)}catch(f){}this.I=!0;this.H=!1;this.ha=-1}Ya(){this.H||this.I||this.T()||(this.N=this.Ea(),this.V&&(this.N%=this.ea()),this.H=!0,this.j.stop(0))}Db(){!this.H||this.I||this.T()||(V(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.bb=this.j,this.j.onended=this.$b,this.j.loop=this.V,this.Ob(),this.Ia(),this.j.start(0,this.N),this.bc=this.Ab(),this.ac=this.N,this.H=!1)}rc(){return super.rc()*this.fd}Nb(){this.fd=this.Ka||this.Cb()?0:1;this.Ob()}xc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Ia(){let f=this.sa;this.cd&&(f*=this.i.jc);this.j&&(this.j.playbackRate.value=f)}wc(f){this.I||this.T()||(this.H?this.N=f:(this.Ya(),this.N=f,this.Db()))}sc(){return this.N}yc(f){f?
this.IsPlaying()?(this.ma=!0,this.N=this.Ea(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ma=!1:this.ma&&(V(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.bb=this.j,this.j.onended=this.$b,this.j.loop=this.V,this.Ob(),this.Ia(),this.j.start(0,this.N),this.bc=this.Ab(),this.ac=this.N,this.ma=!1)}Gc(f){super.Gc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.c=a.W();this.Xd=-1;this.R=this.Y="";this.g=null}f(){this.c=null}lg(a){this.Xd=a}tg(a){this.Y=a}o(){return this.c.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.c.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Va(){return{type:this.R,tag:this.Y,params:this.g}}}
self.te=class extends f{constructor(a,b,d,g,n,q,w){super(a);this.R="filter";this.g=[b,d,g,n,q,w];this.l=this.o();this.b=this.o();this.b.gain.value=w;this.a=this.o();this.a.gain.value=1-w;this.A=this.c.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=g;this.A.Q.value=n;this.A.gain.vlaue=q;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}f(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,g)}}};self.re=class extends f{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.ob=this.o();this.U=this.c.createDelay(b);this.U.delayTime.value=b;this.fb=this.o();this.fb.gain.value=d;this.l.connect(this.ob);this.l.connect(this.a);this.ob.connect(this.b);this.ob.connect(this.U);this.U.connect(this.fb);this.fb.connect(this.ob)}f(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.ob.disconnect();this.U.disconnect();this.fb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const n=self.da.sd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.fb.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.qe=class extends f{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Sd=this.Rd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.eb=this.c.createConvolver();this.eb.normalize=d;this.eb.buffer=b;this.l.connect(this.eb);this.l.connect(this.a);this.eb.connect(this.b)}f(){this.l.disconnect();this.eb.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}hg(a,b){this.Rd=a;this.Sd=b}Va(){const a=
super.Va();a.bufferOriginalUrl=this.Rd;a.bufferUrl="";a.bufferType=this.Sd;return a}};self.ue=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="flanger";this.g=[b,d,g,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.hb=this.o();this.hb.gain.value=n;this.U=this.c.createDelay(b+d);this.U.delayTime.value=b;this.v=this.c.createOscillator();this.v.frequency.value=g;this.J=this.o();this.J.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.hb);this.hb.connect(this.U);this.v.connect(this.J);this.J.connect(this.U.delayTime);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.U.disconnect();this.v.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();this.hb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.J.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.v.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.hb.gain,b/100,d,g)}}};self.we=class extends f{constructor(a,b,d,g,n,q,w){super(a);this.R="phaser";this.g=[b,d,g,n,q,w];this.l=this.o();this.a=this.o();this.a.gain.value=1-w/2;this.b=this.o();this.b.gain.value=w/2;this.A=this.c.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=g;this.v=this.c.createOscillator();this.v.frequency.value=q;this.J=this.o();this.J.gain.value=n;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.v.connect(this.J);this.J.connect(this.A.frequency);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.A.disconnect();this.v.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.J.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.v.frequency,b,d,g)}}};self.ve=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const n=self.da.sd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.ye=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.v=this.c.createOscillator();this.v.frequency.value=b;this.J=this.o();this.J.gain.value=d/2;this.v.connect(this.J);this.J.connect(this.h.gain);this.v.start(0)}f(){this.v.stop(0);this.v.disconnect();
this.J.disconnect();this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.J.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,g)}}};self.xe=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.ub=this.o();this.ub.gain.value=
0;this.v=this.c.createOscillator();this.v.frequency.value=b;this.v.connect(this.ub.gain);this.v.start(0);this.l.connect(this.ub);this.l.connect(this.a);this.ub.connect(this.b)}f(){this.v.stop(0);this.v.disconnect();this.ub.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,g)}}};self.se=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="distortion";this.g=[b,d,g,n,q];this.l=this.o();this.fc=this.o();this.ec=this.o();this.ig(g,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.kc=this.c.createWaveShaper();this.Wc=new Float32Array(65536);this.qf(b,d);this.kc.curve=this.Wc;this.l.connect(this.fc);this.l.connect(this.a);this.fc.connect(this.kc);this.kc.connect(this.ec);
this.ec.connect(this.b)}f(){this.l.disconnect();this.fc.disconnect();this.kc.disconnect();this.ec.disconnect();this.b.disconnect();this.a.disconnect();super.f()}ig(a,b){.01>a&&(a=.01);this.fc.gain.value=a;this.ec.gain.value=Math.pow(1/a,.6)*b}qf(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.vg(g,a,b);this.Wc[32768+d]=g;this.Wc[32768-d-1]=-g}}vg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.Mg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.pe=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="compressor";this.g=[b,d,g,n,q];this.h=this.c.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=q}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.oe=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.c.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Vd=new Float32Array(this.h.frequencyBinCount);this.he=new Uint8Array(b);this.fe=this.Oa=0;this.i.Ze(this)}f(){this.i.bg(this);this.h.disconnect();super.f()}Ga(){this.h.getFloatFrequencyData(this.Vd);this.h.getByteTimeDomainData(this.he);const a=this.h.fftSize;let b=this.Oa=0;for(var d=0;d<a;++d){let g=(this.he[d]-128)/128;0>g&&(g=-g);
this.Oa<g&&(this.Oa=g);b+=g*g}d=self.da.Pe;this.Oa=d(this.Oa);this.fe=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ie(){return{tag:this.Y,index:this.Xd,peak:this.Oa,rms:this.fe,binCount:this.h.frequencyBinCount,freqBins:this.Vd}}}}"use strict";function W(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>u(f,"sw-message",a.data))}
function X(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.fa.Da(class extends self.ua{constructor(f){super(f,"browser");this.s="";K(this,[["get-initial-state",a=>this.Lc(a)],["ready-for-sw-messages",()=>W(this)],["alert",a=>this.Hc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Oc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>X(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===
b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.ah||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.fa.Mb(!0),
this.u.Sc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",
()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.fa.Mb(!1),this.u.Sc({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{u(this,"backbutton")})}Lc(f){this.s=f.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}Hc(f){alert(f.message)}Oc(f){f=f.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});"use strict";
self.fa.Da(class extends self.ua{constructor(f){super(f,"mouse");K(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.u.G.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{u(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{u(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function Y(f,a){a=a.type;let b=!0;0===a?b=await aa():1===a&&(b=await ba());u(f,"permission-result",{type:a,result:b})}async function aa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function ba(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.fa.Da(class extends self.ua{constructor(f){super(f,"touch");I(this,"request-permission",a=>Y(this,a))}});"use strict";
async function ca(f){if(!f.Ba)try{f.Ba=await navigator.wakeLock.request("screen"),f.Ba.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");f.Ba=null;u(f,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),u(f,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),u(f,"wake-lock-error")}}
function Z(){var f=document.body;const a=f.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");f=getComputedStyle(f);f=[f.getPropertyValue("--temp-sai-top"),f.getPropertyValue("--temp-sai-right"),f.getPropertyValue("--temp-sai-bottom"),f.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return f}
self.fa.Da(class extends self.ua{constructor(f){super(f,"platform-info");K(this,[["get-initial-state",()=>this.Lc()],["request-wake-lock",()=>ca(this)],["release-wake-lock",()=>{this.Ba&&(this.Ba.release(),this.Ba=null)}]]);window.addEventListener("resize",()=>{u(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Z()})});this.Ba=null}Lc(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Z(),supportsWakeLock:!!navigator.wakeLock}}});
